webserver:
  port: "WEBSERVER__PORT"
  endpoint: "WEBSERVER__ENDPOINT"
  subscriptions: "WEBERVER__SUBCRIPTIONS"

prisma:
  endpoint: "PRISMA__ENDPOINT"
  secret: "PRISMA__SECRET"
  debug:
    __name: "PRISMA__DEBUG"
    __format: "json"

commander:
  enabled:
    __name: "COMMANDER__ENABLED"
    __format: "json"
  host: "COMMANDER__HOST"
  port: "COMMANDER__PORT"

elasticsearch:
  enabled:
    __name: "ELASTICSEARCH__ENABLED"
    __format: "json"
  client:
    host: "ELASTICSEARCH__CLIENT__HOST"
    log: "ELASTICSEATCH__CLIENT__LOG"
  mockInDevelopment:
    __name: "ELASTICSEARCH__MOCK_IN_DEVELOPMENT"
    __format: "json"

email:
  enabled:
    __name: "EMAIL__ENABLED"
    __format: "json"
  preview:
    __name: "EMAIL__PREVIEW"
    __format: "json"
  reply: "EMAIL__REPLY"
  smtpUrl: "EMAIL__SMTP_URL"

stripe:
  enabled:
    __name: "STRIPE_ENABLED"
    __format: "json"
  secretKey: "STRIPE_SECRET_KEY"

repository: "REPOSITORY"

helm:
  baseDomain: "HELM__BASE_DOMAIN"
  registryAuthSecret: "HELM__REGISTRY_AUTH_SECRET"
  acme:
    __name: "HELM__ACME"
    __format: "json"
  rbacEnabled:
    __name: "HELM__RBAC_ENABLED"
    __format: "json"
  releaseName: "HELM__RELEASE_NAME"
  releaseNamespace: "HELM__RELEASE_NAMESPACE"
  releaseVersion: "HELM__RELEASE_VERSION"
  singleNamespace:
    __name: "HELM__SINGLE_NAMESPACE"
    __format: "json"

auth:
  local:
    enabled:
      __name: "AUTH__LOCAL__ENABLED"
      __format: "json"
  auth0:
    enabled:
      __name: "AUTH__AUTH0__ENABLED"
      __format: "json"
    clientId: "AUTH__AUTH0__CLIENT_ID"
    baseDomain: "AUTH__AUTH0__BASE_DOMAIN"
  google:
    enabled:
      __name: "AUTH__GOOGLE__ENABLED"
      __format: "json"
    clientId: "AUTH__GOOGLE__CLIENT_ID"
  github:
    enabled:
      __name: "AUTH__GITHUB__ENABLED"
      __format: "json"
  okta:
    enabled:
      __name: "AUTH__OKTA__ENABLED"
      __format: "json"
    clientId: "AUTH__OKTA__CLIENT__ID"
    baseDomain: "AUTH__OKTA__BASE__DOMAIN"

jwt:
  passphrase: "JWT__PASSPHRASE"
  certPath: "JWT__CERT_PATH"
  authDuration: "JWT__AUTH_DURATION"

  registry:
    certPath: "JWT__REGISTRY__CERT_PATH"
    issuer: "JWT__REGISTRY__ISSUER"
    service: "JWT__REGISTRY__SERVICE"

publicSignups:
  __name: "PUBLIC_SIGNUPS"
  __format: "json"

emailConfirmation:
  __name: "EMAIL_CONFIRMATION"
  __format: "json"

deployments:
  logHelmValues:
    __name: "DEPLOYMENTS__LOG_HELM_VALUES"
    __format: "json"
  database:
    enabled:
      __name: "DEPLOYMENTS__DATABASE__ENABLED"
      __format: "json"
    retainOnDelete:
      __name: "DEPLOYMENTS__DATABASE__RETAIN_ON_DELETE"
      __format: "json"
    allowRootAccess:
      __name: "DEPLOYMENTS__DATABASE__ALLOW_ROOT_ACCESS"
      __format: "json"
    connection: "DEPLOYMENTS__DATABASE__CONNECTION"
