webserver:
  port: "WEBSERVER__PORT"
  endpoint: "WEBSERVER__ENDPOINT"
  subscriptions: "WEBERVER__SUBCRIPTIONS"

prisma:
  endpoint: "PRISMA_ENDPOINT"
  secret: "PRISMA_SECRET"
  debug:
    __name: "PRISMA_DEBUG"
    __format: "json"

commander:
  enabled:
    __name: "COMMANDER_ENABLED"
    __format: "json"
  host: "COMMANDER_HOST"
  port: "COMMANDER_PORT"

email:
  enabled:
    __name: "EMAIL_ENABLED"
    __format: "json"
  preview:
    __name: "EMAIL_PREVIEW"
    __format: "json"
  reply: "EMAIL_REPLY"
  smtpUrl: "EMAIL_SMTP_URL"

registry:
  auth:
    __name: "REGISTRY_AUTH"
    __format: "json"
  certPath: "REGISTRY_CERT_PATH"
  issuer: "REGISTRY_ISSUER"
  service: "REGISTRY_SERVICE"

repository: "REPOSITORY"

helm:
  baseDomain: "HELM_BASE_DOMAIN"
  registryAuthSecret: "HELM_REGISTRY_AUTH_SECRET"
  acme:
    __name: "HELM_ACME"
    __format: "json"
  rbacEnabled:
    __name: "HELM_RBAC_ENABLED"
    __format: "json"
  releaseName: "HELM_RELEASE_NAME"
  releaseNamespace: "HELM_RELEASE_NAMESPACE"
  releaseVersion: "HELM_RELEASE_VERSION"
  singleNamespace:
    __name: "HELM_SINGLE_NAMESPACE"
    __format: "json"

auth:
  local:
    enabled:
      __name: "AUTH_LOCAL_ENABLED"
      __format: "json"
  auth0:
    enabled:
      __name: "AUTH_AUTH0_ENABLED"
      __format: "json"
    clientId: "AUTH_AUTH0_CLIENT_ID"
    baseDomain: "AUTH_AUTH0_BASE_DOMAIN"
  google:
    enabled:
      __name: "AUTH_GOOGLE_ENABLED"
      __format: "json"
    clientId: "AUTH_GOOGLE_CLIENT_ID"
  github:
    enabled:
      __name: "AUTH_GITHUB_ENABLED"
      __format: "json"

jwtPassphrase: "JWT_PASSPHRASE"

authDuration: "AUTH_DURATION"

publicSignups:
  __name: "PUBLIC_SIGNUPS"
  __format: "json"

emailConfirmation:
  __name: "EMAIL_CONFIRMATION"
  __format: "json"

deployments:
  logHelmValues:
    __name: "DEPLOYMENTS_LOG_HELM_VALUES"
    __format: "json"
  database:
    enabled:
      __name: "DEPLOYMENTS_DATBASE_ENABLED"
      __format: "json"
    retainOnDelete:
      __name: "DEPLOYMENTS_DATBASE_RETAIN_ON_DELETE"
      __format: "json"
    allowRootAccess:
      __name: "DEPLOYMENTS_DATBASE_ALLOW_ROOT_ACCES"
      __format: "json"
    connection: "DEPLOYMENTS_DATABASE_CONNECTION"
