webserver:
  port: "WEBSERVER_PORT"
  endpoint: "WEBSERVER_ENDPOINT"
  subscriptions: "WEBERVER_SUBCRIPTIONS"

repository: "REPOSITORY"

helm:
  baseDomain: "HELM_BASE_DOMAIN"
  registryAuthSecret: "HELM_REGISTRY_AUTH_SECRET"
  acme: "HELM_ACME"
  rbacEnabled: "HELM_RBAC_ENABLED"
  releaseName: "HELM_RELEASE_NAME"
  releaseNamespace: "HELM_RELEASE_NAMESPACE"
  releaseVersion: "HELM_RELEASE_VERSION"

jwtPassphrase: "JWT_PASSPHRASE"
