# API webserver configuration.
webserver:
  port: 8871
  endpoint: "/v1"
  subscriptions: "/ws"

# Prisma configuration.
prisma:
  debug: false

# Commander configuration.
commander:
  enabled: false
  host: localhost
  port: 50051

# Charts live here.
# This is where the airflow chart is installed from.
repository: "https://helm.astronomer.io/"

# Helm configuration.
# These values are set at runtime and used for airflow deployments.
helm:
  baseDomain: ~
  registryAuthSecret: ~
  acme: ~
  rbacEnabled: ~
  releaseName: ~
  releaseNamespace: ~
  releaseVersion: ~
  singleNamespace: false

# Auth configuration.
auth:
  # Local database (user/pass) configuration.
  local:
    enabled: true

  # Auth0 integration configuration.
  auth0:
    enabled: false
    clientId: ~
    baseDomain: ~
    externalLogin: ~

  # Direct oauth integration to google.
  google:
    enabled: false
    clientId: ~

# Passphrase to sign JWTs with.
jwtPassphrase: ~

# JWT / Cookie duration in milliseconds.
authDuration: 86400000

# Allow public signups.
publicSignups: false

# Require email confirmation.
emailConfirmation: true

# Format: ${SCOPE}.${RESOURCE}.${VERB}
roles:
  #
  # System
  #
  - id: SYSTEM_ADMIN
    name: System Admin
    permissions:
      - global.systemSettings.create
      - global.systemSettings.get
      - global.systemSettings.list
      - global.systemSettings.update
      - global.systemSettings.delete
      - global.workspace.get
      - global.workspace.list
      - global.workspace.update
      - global.workspace.delete
      - global.deployment.get
      - global.deployment.list
      - global.deployment.update
      - global.deployment.delete

  - id: SYSTEM_EDITOR
    name: System Editor
    permissions:
      - global.systemSettings.get
      - global.systemSettings.list
      - global.systemSettings.update

  - id: SYSTEM_VIEWER
    name: System Viewer
    permissions:
      - global.systemSettings.get
      - global.systemSettings.list

  #
  # User
  #
  - id: USER
    name: User
    permissions:
      - user.workspace.create
      - user.workspace.list
      - user.deployment.create
      - user.deployment.list

  # Workspace
  - id: WORKSPACE_ADMIN
    name: Workspace Admin
    permissions:
      - user.workspace.get
      - user.workspace.update
      - user.workspace.delete

  - id: WORKSPACE_EDITOR
    name: Workspace Editor
    permissions:
      - user.workspace.get
      - user.workspace.update

  - id: WORKSPACE_VIEWER
    name: Workspace Viewer
    permissions:
      - user.workspace.get

  # Deployment
  - id: DEPLOYMENT_ADMIN
    name: Deployment Admin
    permissions:
      - user.deployment.get
      - user.deployment.update
      - user.deployment.delete

  - id: DEPLOYMENT_EDITOR
    name: Deployment Editor
    permissions:
      - user.deployment.get
      - user.deployment.update

  - id: DEPLOYMENT_VIEWER
    name: Deployment Viewer
    permissions:
      - user.deployment.get

#
# Airflow Deployment Configurations
#
deployments:
  # An astro unit defines the smallest billable unit
  # in the system. Default values are based on
  # the GCP n1-standard-1. CPU should always be expressed
  # in millicpu and memory should be expressed in Mibibytes.
  astroUnit:
    cpu: 100
    memory: 384
    pods: 1
    airflowConns: 5
    actualConns: 0.5
    # price: 10

  # This defines how much extra capacity, in astro units,
  # that a user can expand a deployment to. This is currently
  # represented as a slider in the UI.
  maxExtraAu: 400

  # This defines all possible components for an airflow
  # deployment and the default AU to use for the kubernetes 
  # resource requests, as well as its limits.
  components:
    - name: scheduler
      au:
        default: 5
        limit: 30
    - name: webserver
      au:
        default: 2
        limit: 30
    - name: statsd
      au:
        default: 2
        limit: 30
    - name: pgbouncer
      au:
        default: 2
        limit: 2
    - name: flower
      au:
        default: 2
        limit: 2
    - name: redis
      au:
        default: 2
        limit: 2
    - name: workers
      au:
        default: 10
        limit: 30
      extra:
        - name: terminationGracePeriodSeconds
          default: 600
          limit: 36000
        - name: replicas
          default: 1
          limit: 10

  # This defines which executors should be supported, as well
  # as the components required to run a particular
  # executor configuration.
  executors:
    - name: LocalExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
    - name: CeleryExecutor
      enabled: true
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
        - workers
        - flower
        - redis
    - name: KubernetesExecutor
      enabled: false
      components:
        - scheduler
        - webserver
        - statsd
        - pgbouncer
