# API webserver configuration.
webserver:
  port: 8871
  endpoint: "/v1"
  subscriptions: "/ws"

# Commander configuration.
commander:
  enabled: false

# Set the length of a Cloud Trial
trial:
  # Cloud trial is 2 weeks in milliseconds
  length: 12096e5
# Charts live here.
# This is where the airflow chart is installed from.
repository: "https://helm.astronomer.io/"

# Helm configuration.
# These values are set at runtime and used for airflow deployments.
helm:
  baseDomain: astronomer.io
  acme: ~
  rbacEnabled: ~
  releaseName: ~
  releaseNamespace: ~
  releaseVersion: ~

# Auth configuration.
auth:
  # Local database (user/pass) configuration.
  local:
    enabled: true

  # Auth0 integration configuration.
  auth0:
    enabled: true
    clientId: ~
    baseDomain: ~
    externalLogin: ~

  # Direct oauth integration to google.
  google:
    enabled: true
    clientId: ~

  # Direct oauth integration to github (WIP).
  github:
    enabled: false

# Passphrase to sign JWTs with.
jwt:
  passphrase: "abcdefg"

  # JWT / Cookie duration in milliseconds.
  authDuration: 86400000
  certPath: ./test-data/certs/

# Deployment configuration.
deployments:
  database:
    enabled: false

# Stripe configuration.
stripe:
  enabled: true
